# Generated by Django 3.1.2 on 2020-12-29 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('descriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
